find_path( angelscript_INCLUDE angelscript.h HINTS "${PROJECT_SOURCE_DIR}/dependency/AngelScript/angelscript/include" )
find_library( angelscript_LIBRARY_STATIC libangelscript.a angelscript.lib HINTS  "${PROJECT_SOURCE_DIR}/dependency/AngelScript/angelscript/projects/cmake" )

if ( angelscript_INCLUDE AND angelscript_LIBRARY_STATIC )
    set( ANGELSCRIPT_FOUND TRUE )
    message( STATUS "Found AngelScript include at: ${angelscript_INCLUDE}" )
    message( STATUS "Found AngelScript library at: ${angelscript_LIBRARY_STATIC}" )
else ( )
    message( FATAL_ERROR "Failed to locate AngelScript dependency." )
endif ( )
